### ISSUE TITLE
Punto 2

### ISSUE THREAD

**Issue by KarolBurbanoN** [VeronicaMujica/MiniProyecto-4#3]
En una empresa de logística, se necesita optimizar la gestión de inventario en su almacén. El almacén maneja una gran cantidad de productos diferentes y necesita un sistema eficiente para realizar un seguimiento del inventario disponible, así como para realizar operaciones de entrada y salida de productos de manera rápida y eficaz.

El objetivo es minimizar el tiempo de búsqueda y acceso a los productos en el almacén. Se desea diseñar un sistema de gestión de inventario que asigne de manera eficiente las ubicaciones de almacenamiento a cada producto. Cada producto tiene un código único y una cantidad asociada.

El sistema debe ser capaz de realizar operaciones de búsqueda y actualización del inventario en tiempo constante,
independientemente del tamaño del almacén o la cantidad de productos almacenados. El diseño del sistema debe tener en cuenta la posibilidad de cambios en el inventario, como la adición de nuevos productos o la eliminación de productos existentes, y garantizar que el tiempo de acceso a los productos se mantenga óptimo incluso después de realizar cambios en el inventario.

Al finalizar el proceso, se deben guardar los productos del almacén en un archivo de texto

**Comment by JeidyMurillo** [comment]
En este ejercicio de gestión de inventario en una empresa de logística, Se utilizó la estructura HashMap. La razón detrás de esta elección es:

**1. Eficiencia de Búsqueda y Actualización:**

- 	El HashMap permite realizar operaciones de búsqueda, inserción y eliminación en tiempo promedio constante, lo cual es crucial para mantener un sistema de inventario eficiente.

**2.	Clave Única (Código de Producto):**

- 	Usar el código del producto como clave en el HashMap asegura que cada producto se pueda identificar de manera única y acceder rápidamente.

**3.	Flexibilidad de Gestión:**

- 	La estructura HashMap facilita la gestión de productos, permitiendo adiciones, actualizaciones y eliminaciones de manera sencilla.

Este enfoque garantiza un acceso rápido y eficiente a los productos en el inventario, manteniendo la estructura y las operaciones simples y claras.
